# Generated by Django 3.2.9 on 2022-02-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=30)),
                ('issuer', models.CharField(max_length=10)),
                ('card_number', models.CharField(max_length=16)),
                ('card_holder_name', models.CharField(max_length=150)),
                ('cvc', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=13)),
                ('city', models.CharField(max_length=13)),
                ('expiry_date', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=13)),
                ('country', models.CharField(max_length=13)),
                ('postal_code', models.CharField(max_length=13)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
