# Generated by Django 3.2.9 on 2022-02-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('type', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=10)),
                ('is_unread', models.BooleanField(default=False)),
                ('avatar', models.CharField(blank=True, max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
