# Generated by Django 3.2.9 on 2022-02-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
                ('uid', models.CharField(max_length=30)),
                ('public_key', models.CharField(max_length=30)),
                ('private_key', models.CharField(max_length=30)),
                ('wallet_address', models.CharField(max_length=30)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
